workflows:
  ios-kmp-build:
    name: Build iOS App (KMP)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      java: 17
      xcode: latest
    scripts:
      - name: Set execution permission for gradlew
        script: chmod +x gradlew
      - name: Generate SQLDelight Code
        script: ./gradlew generateSqlDelightInterface
      - name: Build iOS App
        script: |
          PROJ_PATH=$(find . -name "*.xcodeproj" -maxdepth 3 | head -n 1)
          xcodebuild -project "$PROJ_PATH" \
                     -scheme iosApp \
                     -sdk iphoneos \
                     -configuration Release \
                     CODE_SIGNING_ALLOWED=NO \
                     OTHER_LDFLAGS='$(inherited) -lsqlite3' \
                     build
          # ضغط التطبيق لملف zip واحد لسهولة التنزيل والرفع
          cd /Users/builder/Library/Developer/Xcode/DerivedData/*/Build/Products/Release-iphoneos
          zip -r Catalog2-iOS.zip *.app
    artifacts:
      - /Users/builder/Library/Developer/Xcode/DerivedData/*/Build/Products/Release-iphoneos/*.zip